# configure directives can be used to set constants
# that are available in each of your views
configure do

  # Global vars
  Sample = "Test"
  Version = Sinatra::VERSION

  # Syte social networks api keys
  # Blog Integration: Tumblr
  TUMBLR_BLOG_URL = '[ENTER TUMBLR BLOG URL] ex. rigoneri.tumblr.com'
  #TUMBLR_API_URL = 'http://api.tumblr.com/v2/blog/{0}'.format(TUMBLR_BLOG_URL)
  TUMBLR_API_KEY = '[ENTER TUMBLR API KEY HERE, SEE TUMBLR SETUP INSTRUCTIONS]'

  #RSS Feed Integration: (by default use Tumbrl rss feed)
  RSS_FEED_ENABLED = true
  #RSS_FEED_URL = 'http://{0}/rss'.format(TUMBLR_BLOG_URL)

  #Twitter Integration
  TWITTER_INTEGRATION_ENABLED = true
  TWITTER_API_URL             = 'https://api.twitter.com/'
  TWITTER_CONSUMER_KEY        = '[ENTER TWITTER CONSUMER KEY HERE, SEE TWITTER SETUP INSTRUCTIONS]'
  TWITTER_CONSUMER_SECRET     = '[ENTER TWITTER CONSUMER SECRET HERE, SEE TWITTER SETUP INSTRUCTIONS]'
  TWITTER_USER_KEY            = '[ENTER TWITTER USER KEY HERE, SEE TWITTER SETUP INSTRUCTIONS]'
  TWITTER_USER_SECRET         = '[ENTER TWITTER USER SECRET HERE, SEE TWITTER SETUP INSTRUCTIONS]'

  # Facebook Integration
  FACEBOOK_INTEGRATION_ENABLED = true
  FACEBOOK_KEY    = '[ENTER FACEBOOK_KEY, SEE FACEBOOK APP SETUP INSTRUCTIONS]'
  FACEBOOK_SECRET = '[ENTER TWITTER USER SECRET HERE, SEE TWITTER SETUP INSTRUCTIONS]'
  FACEBOOK_ID     = '[ENTER PAGE OR PROFILE ID, SEE FACEBOOK SETUP INSTRUCTIONS]'

  # Behance Integration
  BEHANCE_INTEGRATION = true
  BEHANCE_TOKEN = '[ENTER BEHANCE_TOKEN, SEE BEHANCE SETUP INSTRUCTIONS]'
  
  # Github Integration
  GITHUB_INTEGRATION_ENABLED = true
  GITHUB_API_URL = 'https://api.github.com/'
  GITHUB_ACCESS_TOKEN = '[ENTER GITHUB ACCESS TOKEN HERE, SEE GITHUB SETUP INSTRUCTIONS]'

  GITHUB_OAUTH_ENABLED = true
  GITHUB_CLIENT_ID = '[ENTER GITHUB CLIENT ID HERE, SEE GITHUB SETUP INSTRUCTIONS]'
  GITHUB_CLIENT_SECRET = '[ENTER GITHUB CLIENT SECRET HERE, SEE GITHUB SETUP INSTRUCTIONS]'
  GITHUB_OAUTH_AUTHORIZE_URL = 'https://github.com/login/oauth/authorize'
  GITHUB_OAUTH_ACCESS_TOKEN_URL = 'https://github.com/login/oauth/access_token'


  #Dribbble Integration
  DRIBBBLE_INTEGRATION_ENABLED = true
  DRIBBBLE_API_URL = 'http://api.dribbble.com/players/'


  #Instagram Integration
  INSTAGRAM_INTEGRATION_ENABLED = true
  INSTAGRAM_API_URL = 'https://api.instagram.com/v1/'
  INSTAGRAM_ACCESS_TOKEN = '[ENTER INSTAGRAM ACCESS TOKEN HERE, SEE INSTAGRAM SETUP INSTRUCTIONS]'
  INSTAGRAM_USER_ID = '[ENTER INSTAGRAM USER_ID HERE, SEE INSTAGRAM SETUP INSTRUCTIONS]'

  INSTAGRAM_OAUTH_ENABLED = true
  INSTAGRAM_CLIENT_ID = '[ENTER INSTAGRAM CLIENT_ID HERE, SEE INSTAGRAM SETUP INSTRUCTIONS]'
  INSTAGRAM_CLIENT_SECRET = '[ENTER INSTAGRAM CLIENT_SECRET HERE, SEE INSTAGRAM SETUP INSTRUCTIONS]'
  INSTAGRAM_OAUTH_AUTHORIZE_URL = 'https://api.instagram.com/oauth/authorize'
  INSTAGRAM_OAUTH_ACCESS_TOKEN_URL = 'https://api.instagram.com/oauth/access_token'


  #Foursquare Integration
  FOURSQUARE_INTEGRATION_ENABLED = true
  FOURSQUARE_API_URL = 'https://api.foursquare.com/v2/'
  FOURSQUARE_ACCESS_TOKEN = '[ENTER FOURSQUARE ACCESS TOKEN HERE, SEE FOURSQUARE SETUP INSTRUCTIONS]'
  FOURSQUARE_SHOW_CURRENT_DAY = true

  FOURSQUARE_OAUTH_ENABLED = true
  FOURSQUARE_CLIENT_ID = '[ENTER FOURSQUARE CLIENT_ID HERE, SEE FOURSQUARE SETUP INSTRUCTIONS]'
  FOURSQUARE_CLIENT_SECRET = '[ENTER FOURSQUARE CLIENT_SECRET HERE, SEE FOURSQUARE SETUP INSTRUCTIONS]'
  FOURSQUARE_OAUTH_AUTHORIZE_URL = 'https://foursquare.com/oauth2/authenticate'
  FOURSQUARE_OAUTH_ACCESS_TOKEN_URL = 'https://foursquare.com/oauth2/access_token'


  #Google Analytics
  GOOGLE_ANALYTICS_TRACKING_ID = ''

  #Woopra
  WOOPRA_TRACKING_DOMAIN = ''
  WOOPRA_TRACKING_IDLE_TIMEOUT = 300000  # 5 minutes
  WOOPRA_TRACKING_INCLUDE_QUERY = false

  #Disqus Integration
  DISQUS_INTEGRATION_ENABLED = false
  DISQUS_SHORTNAME = ''

  #Lastfm Integration
  LASTFM_INTEGRATION_ENABLED = true
  LASTFM_API_URL = 'http://ws.audioscrobbler.com/2.0/'
  LASTFM_API_KEY = '[ENTER LASTFM API_KEY HERE, SEE LASTFM SETUP INSTRUCTIONS]'
  
  # SoundCloud Integration
  SOUNDCLOUD_INTEGRATION_ENABLED = true
  SOUNDCLOUD_API_URL = 'https://api.soundcloud.com/'
  SOUNDCLOUD_CLIENT_ID = '[ENTER SOUNDCLOUD APPLICATION CLIENT_ID HERE]'
  SOUNDCLOUD_SHOW_ARTWORK = FalsetrueOUNDCLOUD_PLAYER_COLOR = 'ff912b'

  #Bitbucket Integration
  BITBUCKET_INTEGRATION_ENABLED = true
  BITBUCKET_API_URL = 'https://api.bitbucket.org/1.0/'
  # Forks count require one connection for each repository,
  # set BITBUCKET_SHOW_FORKS to false to disable
  BITBUCKET_SHOW_FORKS = false

  #Tent.io Integration
  TENT_INTEGRATION_ENABLED = true
  TENT_ENTITY_URI = '[ENTER YOUR ENTITYtrue HERE] ex. https://yourname.tent.is'
  TENT_FEED_URL = '[ENTER A URL TO YOUR FEED] ex. https://yourname.tent.is'

end